# -*- coding: utf-8 -*-
"""Navie_Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQhMJZCQrI7yZsgbG53dX3sCGCPkov4h
"""

import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/spam (1).csv')

df.head()

df.groupby('Category').describe()

df['Category'].value_counts()

"""##We have to convert the category and message to numberic values

"""

df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

df.head()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.25)

"""##Converting the Messages to numerical values as machine can't understand the words or text using countVectorizer

##CountVectorizer extracts unique words from the corpus and builds a document-term matrix where each cell represents the frequency of a word in a sentence/document.
"""

from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_count=v.fit_transform(x_train.values)
x_train_count.toarray()[:10]

from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_count,y_train)

emails=["	Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]
emails_count=v.transform(emails)
model.predict(emails_count)

x_test_count=v.transform(x_test)
model.score(x_test_count,y_test)

"""##PIPELINE"""

from sklearn.pipeline import Pipeline
clf=Pipeline([
              ('vectorizer',CountVectorizer()),
              ('nb',MultinomialNB())
])

clf.fit(x_train,y_train)

clf.score(x_test,y_test)